export const LOGIN_USER = "LOGIN_USER";

export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";
export const FILTERED_JOBS = "FILTERED_JOBS";

export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";

export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES";

export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";

export const RECEIVE_DEGREES = "RECEIVE_DEGREES";
export const FETCH_DEGREES = "FETCH_DEGREES";
export const UNIQUE_DEGREES = "UNIQUE_DEGREES";
export const INCLUDE_JOB_BY_DEGREE = "INCLUDE_JOB_BY_DEGREE";
export const ADD_SELECTED_DEGREE = "ADD_SELECTED_DEGREE";

export const CLEAR_USER_JOB_FILTER_SECTIONS = "CLEAR_USER_JOB_FILTER_SECTIONS";

export const UPDATE_SKILLS_SEARCH_TERM = "UPDATE_SKILLS_SEARCH_TERM";
export const INCLUDE_JOB_BY_SKILL = "INCLUDE_JOB_BY_SKILL";

export const UPDATE_SKILLS_SEARCH_LOCATIONS = "UPDATE_SKILLS_SEARCH_LOCATIONS";
export const INCLUDE_JOB_BY_LOCATIONS = "INCLUDE_JOB_BY_LOCATIONS";

export const FETCH_SPOTLIFGT = "FETCH_SPOTLIFGT";
